-- Database Export: library_project
-- Generated by LocalDevine
-- Date: 2026-02-19T18:14:01.309Z

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- Table: books
DROP TABLE IF EXISTS `books`;
CREATE TABLE `books` (
  `BookID` int(11) NOT NULL AUTO_INCREMENT,
  `BookName` varchar(200) NOT NULL,
  `Author` varchar(200) NOT NULL,
  `Category` varchar(200) NOT NULL,
  `StatusID` tinyint(1) NOT NULL,
  PRIMARY KEY (`BookID`),
  KEY `BookName` (`BookName`),
  KEY `StatusID` (`StatusID`),
  CONSTRAINT `books_ibfk_1` FOREIGN KEY (`StatusID`) REFERENCES `borrowing` (`StatusID`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `books` (`BookID`, `BookName`, `Author`, `Category`, `StatusID`) VALUES
(1, 'หนังสือเรียนรายวิชาพื้นฐาน พระพุทธศาสนา ชั้นมัธยมศึกษาปีที่ ๔-๖', 'รศ. ดร.ธีระพงษ์ มีไธสง และคณะ', 'สังคม ศาสนา และวัฒนธรรม', 1);

-- Table: borrowing
DROP TABLE IF EXISTS `borrowing`;
CREATE TABLE `borrowing` (
  `BorrowID` int(11) NOT NULL AUTO_INCREMENT,
  `UserID` int(11) DEFAULT NULL,
  `BookID` int(11) DEFAULT NULL,
  `FullName` varchar(200) DEFAULT NULL,
  `BookName` varchar(200) DEFAULT NULL,
  `ReturnBefore` date NOT NULL,
  `BorrowedDate` date NOT NULL,
  `ReturnedDate` date DEFAULT NULL,
  `StatusID` tinyint(1) NOT NULL,
  PRIMARY KEY (`BorrowID`),
  KEY `UserID` (`UserID`),
  KEY `BookID` (`BookID`),
  KEY `StatusID` (`StatusID`),
  KEY `FullName` (`FullName`),
  KEY `BookName` (`BookName`),
  CONSTRAINT `borrowing_ibfk_5` FOREIGN KEY (`UserID`) REFERENCES `users` (`UserID`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `borrowing_ibfk_6` FOREIGN KEY (`BookID`) REFERENCES `books` (`BookID`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `borrowing_ibfk_7` FOREIGN KEY (`FullName`) REFERENCES `users` (`FullName`) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT `borrowing_ibfk_8` FOREIGN KEY (`BookName`) REFERENCES `books` (`BookName`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `borrowing` (`BorrowID`, `UserID`, `BookID`, `FullName`, `BookName`, `ReturnBefore`, `BorrowedDate`, `ReturnedDate`, `StatusID`) VALUES
(2, 1, 1, NULL, NULL, '2026-02-20 00:00:00.000', '2026-02-13 00:00:00.000', NULL, 1);

-- Table: settings
DROP TABLE IF EXISTS `settings`;
CREATE TABLE `settings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `setting_key` varchar(50) NOT NULL,
  `setting_value` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `setting_key` (`setting_key`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `settings` (`id`, `setting_key`, `setting_value`, `created_at`) VALUES
(1, 'site_name', 'library', '2026-02-09 21:21:14.000'),
(2, 'site_version', '1.0.0', '2026-02-09 21:21:14.000');

-- Table: users
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `UserID` int(11) NOT NULL AUTO_INCREMENT,
  `Username` varchar(100) NOT NULL,
  `Password` varchar(255) NOT NULL,
  `FullName` varchar(200) NOT NULL,
  `Email` varchar(100) NOT NULL,
  `Phone` varchar(20) NOT NULL,
  `Role` tinyint(1) NOT NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE KEY `Username` (`Username`),
  KEY `FullName` (`FullName`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `users` (`UserID`, `Username`, `Password`, `FullName`, `Email`, `Phone`, `Role`) VALUES
(1, 'phop12345', '1234567', 'นายปองภพ รอดตัวดี', '54212@sakolraj.ac.th', '0655985993', 1);

SET FOREIGN_KEY_CHECKS = 1;
